package com.amazon.device.ads;

import com.iab.omid.library.amazon.Omid;
import com.ironsource.mediationsdk.utils.IronSourceConstants;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/* compiled from: r8-map-id-329fa88356c9e071bedcd87e8cbc16a4cb0c028932e63902b8210957806638ae */
/* loaded from: classes2.dex */
public class DtbConstants {
    public static final String AAX_HOSTNAME;
    public static String AAX_ROUTE53_ENABLED_CNAME = null;
    public static final String ADMOB_HEIGHT_KEY = "amazon_custom_event_height";
    public static final long ADMOB_REQUESTID_MAP_CLEAR_INTERVAL = 29000;
    public static final String ADMOB_REQUEST_ID_KEY = "amazon_custom_event_request_id";
    public static final String ADMOB_SLOTGROUP_KEY = "amazon_custom_event_slot_group";
    public static final String ADMOB_SLOTUUID_KEY = "amazon_custom_event_slot_uuid";
    public static final String ADMOB_SLOT_INFO_EXTRA_KEY = "amazon_custom_event_slot_info_extra";
    public static final String ADMOB_WIDTH_KEY = "amazon_custom_event_width";
    public static final String ADMOB_iSVIDEO_KEY = "amazon_custom_event_is_video";
    public static final String AD_TRACKING_ENABLED = "ad-tracking";
    public static final String AMAZON_MOBILE = "amazonmobile";
    public static final String AMZN_BIDDER_NAME_KEY = "bidderName";
    public static final String AMZN_BIDDER_REQUEST_KEY = "sdkb";
    public static final String AMZN_BIDDER_TOKEN_KEY = "token";
    public static final String AMZN_CREATIVE_HEIGHT_KEY = "height";
    public static final String AMZN_CREATIVE_WIDTH_KEY = "width";
    public static final String AMZN_IMP_URL_KEY = "impUrl";
    public static final String AMZN_SDK_BIDDER_ID_KEY = "amznbdr";
    public static final String APS_ADAPTER_VERSION = "amazon_custom_event_adapter_version";
    public static final String APS_ADAPTER_VERSION_2 = "2.0";
    public static final String APS_ADMOB_CONST_CCPA_APS_PRIVACY = "aps_privacy";
    public static final String APS_ADMOB_CONST_CCPA_US_PRIVACY = "us_privacy";
    public static final int APS_ANALYTICS_ADDITIONAL_VALUE_SIZE_LIMIT = 100;
    public static final int BID_TIMEOUT = 5000;
    public static final String CONFIG_CHECK_IN_TTL_FEATURE = "config_check_in_ttl_feature_v2";
    public static final long DEFAULT_CONFIG_CHECK_IN_TTL_IN_MILLISECONDS = 172800000;
    public static final int DEFAULT_PLAYER_HEIGHT = 480;
    public static final int DEFAULT_PLAYER_WIDTH = 320;
    public static final String DSA_PARAM_KEY = "dsa";
    public static final int DTB_BETA = 3;
    public static final String DTB_CONFIG_ENDPOINT = "mads.amazon-adsystem.com";
    public static final String DTB_CONFIG_PATH = "/msdk/getConfig";
    public static final int DTB_DOMAIN = 1;
    public static final int DTB_GAMMA = 2;
    public static final int DTB_PROD = 1;
    public static final String DTB_WEB_RESOURCES = "c.amazon-adsystem.com/";
    public static final String EMPTY_JSON_STRING = "{}";
    public static final int FIREOS_ADTRACKING_NOT_LIMITED = 0;
    public static final String GPS_AVAILABLE_SETTING = "gps-available";
    public static final String HTTP = "http://";
    public static final String HTTPS = "https://";
    public static final String IABCONSENT_CONSENT_STRING = "IABConsent_ConsentString";
    public static final String IABCONSENT_SUBJECT_TO_GDPR = "IABConsent_SubjectToGDPR";
    public static final String IABGPP_GppSID = "IABGPP_GppSID";
    public static final String IABGPP_HDR_GppString = "IABGPP_HDR_GppString";
    public static final String IABTCF_GDPR_APPLIES = "IABTCF_gdprApplies";
    public static final String IABTCF_TC_STRING = "IABTCF_TCString";
    public static final int INTERSTITIAL_HEIGHT = 9999;
    public static final int INTERSTITIAL_WIDTH = 9999;
    public static final String MDTB_NOT_INITIALIZED = "mDTB was not initialized, please use AdRegistration.getInstance(...) before using other SDK calls";
    public static final int MEDIATION_ENCODED_PRICE_POINT_LENGTH = 8;
    public static final String MEDIATION_NAME = "mediationName";
    public static final long MINIMUM_CONFIG_CHECK_IN_TTL_IN_MILLISECONDS = 900000;
    public static final String NATIVE_FRAMEWORK_NAME = "native";
    public static final String NATIVE_OS_NAME = "android";
    public static final int NETWORK_READ_TIMEOUT = 60000;
    public static final String NETWORK_TYPE_LTE = "13";
    public static final String NETWORK_TYPE_UNKNOWN = "0";
    public static final String NETWORK_TYPE_WIFI = "Wifi";
    public static final String OM_JS_ENDPOINT = "video-player.aps.amazon-adsystem.com/";
    public static final String OM_JS_RESOURCE = "static/omsdk/";
    public static final String OM_SDK_DEFAULT_PARTNER_NAME = "Amazon1";
    public static final String OM_SDK_PARTNER_KEY_NAME = "omidPartnerName";
    public static final String OM_SDK_PARTNER_VERSION_KEY_NAME = "omidPartnerVersion";
    public static final String OVERRIDE_PROPERTIES_PATH = "/aps_override_properties/override.properties";
    public static final String PRIVACY_LOCATION_ACCURACY_IN_METERS_KEY = "accuracyInMeters";
    public static final String PRIVACY_LOCATION_COMPUTE_MODE = "Compute";
    public static final String PRIVACY_LOCATION_FIXED_MODE = "Fixed";
    public static final String PRIVACY_LOCATION_KEY = "location";
    public static final String PRIVACY_LOCATION_MODE_KEY = "mode";
    public static final String PRIVACY_LOCATION_RESTRICTED_MODE = "Restricted";
    public static final String REGULATORY_PARAM_KEY = "regs";
    public static Set<String> REMOVE_AAX_END_POINT_FROM_SHARED_PREF = null;
    public static final String SDK_DISTRIBUTION_KEY_NAME = "distribution";
    public static final String SDK_DISTRIBUTION_MARKER_WITH_JSON = "aps_distribution_marker.json";
    public static final String SDK_NAME = "Amazon DTB Ads API";
    public static final String SDK_VERSION = "11.1.0";
    public static final String SDK_VERSION_PREFIX = "aps-android";
    public static final long SIS_CHECKIN_INTERVAL = 86400000;
    public static String SIS_END_POINT = null;
    public static final long SIS_PING_INTERVAL = 2592000000L;
    public static final String SIS_SERVER_PATH = "/api3";
    public static final String UNITY_FRAMEWORK_NAME = "unity";
    public static final String adServerPath = "/e/msdk/ads";
    public static final String adVideoServerPath = "/e/vsdk/ads";
    public static final String displayImpressionPath = "e/msdk/imp";
    public static final String generatePath = "/generate_did";
    public static final String pingPath = "/ping";
    public static final String sisEndPoint = "s.amazon-adsystem.com/api3";
    public static final String updatePath = "/update_dev_info";
    public static final String videoImpressionPath = "e/msdk/impv";
    public static final String INTEGRATED_OM_VERSION = Omid.getVersion().split("-")[0].replace(".", "_");
    public static final List<String> BLACK_LIST = Arrays.asList("status", IronSourceConstants.EVENTS_ERROR_CODE, "instrPixelURL");

    static {
        HashSet hashSet = new HashSet();
        REMOVE_AAX_END_POINT_FROM_SHARED_PREF = hashSet;
        hashSet.add("aax-us-east.amazon-adsystem.com");
        REMOVE_AAX_END_POINT_FROM_SHARED_PREF.add("aax-eu.amazon-adsystem.com");
        REMOVE_AAX_END_POINT_FROM_SHARED_PREF.add("aax-fe-sin.amazon-adsystem.com");
        AAX_HOSTNAME = "aax.amazon-adsystem.com";
        AAX_ROUTE53_ENABLED_CNAME = "aax.amazon-adsystem.com";
        SIS_END_POINT = "s.amazon-adsystem.com";
    }
}
