package com.vungle.ads.internal.model;

import androidx.core.app.NotificationCompat;
import com.applovin.shadow.okio.Segment;
import com.mbridge.msdk.foundation.entity.CampaignEx;
import com.mbridge.msdk.playercommon.exoplayer2.C;
import com.mbridge.msdk.playercommon.exoplayer2.source.ExtractorMediaSource;
import com.vungle.ads.internal.Constants;
import com.vungle.ads.internal.model.AdPayload;
import java.util.List;
import java.util.Map;
import kotlin.jvm.internal.e0;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.ArrayListSerializer;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import tu.f;

/* compiled from: r8-map-id-329fa88356c9e071bedcd87e8cbc16a4cb0c028932e63902b8210957806638ae */
@f
/* loaded from: classes8.dex */
public final class AdPayload$AdUnit$$serializer implements GeneratedSerializer<AdPayload.AdUnit> {
    public static final AdPayload$AdUnit$$serializer INSTANCE;
    public static final /* synthetic */ SerialDescriptor descriptor;

    static {
        AdPayload$AdUnit$$serializer adPayload$AdUnit$$serializer = new AdPayload$AdUnit$$serializer();
        INSTANCE = adPayload$AdUnit$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.vungle.ads.internal.model.AdPayload.AdUnit", adPayload$AdUnit$$serializer, 29);
        pluginGeneratedSerialDescriptor.addElement("id", true);
        pluginGeneratedSerialDescriptor.addElement("ad_type", true);
        pluginGeneratedSerialDescriptor.addElement("ad_source", true);
        pluginGeneratedSerialDescriptor.addElement("expiry", true);
        pluginGeneratedSerialDescriptor.addElement("deeplink_url", true);
        pluginGeneratedSerialDescriptor.addElement("click_coordinates_enabled", true);
        pluginGeneratedSerialDescriptor.addElement("ad_load_optimization", true);
        pluginGeneratedSerialDescriptor.addElement("template_heartbeat_check", true);
        pluginGeneratedSerialDescriptor.addElement("mediation_name", true);
        pluginGeneratedSerialDescriptor.addElement("info", true);
        pluginGeneratedSerialDescriptor.addElement("sleep", true);
        pluginGeneratedSerialDescriptor.addElement("error_code", true);
        pluginGeneratedSerialDescriptor.addElement("tpat", true);
        pluginGeneratedSerialDescriptor.addElement("vm_url", true);
        pluginGeneratedSerialDescriptor.addElement("vm_version", true);
        pluginGeneratedSerialDescriptor.addElement("ad_market_id", true);
        pluginGeneratedSerialDescriptor.addElement("notification", true);
        pluginGeneratedSerialDescriptor.addElement(Constants.LOAD_AD, true);
        pluginGeneratedSerialDescriptor.addElement("viewability", true);
        pluginGeneratedSerialDescriptor.addElement("template_type", true);
        pluginGeneratedSerialDescriptor.addElement("template_settings", true);
        pluginGeneratedSerialDescriptor.addElement(CampaignEx.JSON_KEY_CREATIVE_ID, true);
        pluginGeneratedSerialDescriptor.addElement("app_id", true);
        pluginGeneratedSerialDescriptor.addElement("show_close", true);
        pluginGeneratedSerialDescriptor.addElement("show_close_incentivized", true);
        pluginGeneratedSerialDescriptor.addElement("ad_size", true);
        pluginGeneratedSerialDescriptor.addElement("webview_settings", true);
        pluginGeneratedSerialDescriptor.addElement("use_preloading", true);
        pluginGeneratedSerialDescriptor.addElement("ad_partial_download_enabled", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private AdPayload$AdUnit$$serializer() {
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        KSerializer<?> nullable = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer<?> nullable2 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer<?> nullable3 = BuiltinSerializersKt.getNullable(stringSerializer);
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        KSerializer<?> nullable4 = BuiltinSerializersKt.getNullable(intSerializer);
        KSerializer<?> nullable5 = BuiltinSerializersKt.getNullable(stringSerializer);
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{nullable, nullable2, nullable3, nullable4, nullable5, BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(AdPayload.TpatSerializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(new ArrayListSerializer(stringSerializer)), BuiltinSerializersKt.getNullable(new ArrayListSerializer(stringSerializer)), BuiltinSerializersKt.getNullable(AdPayload$ViewAbility$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(AdPayload$TemplateSettings$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(AdPayload$AdSizeInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(AdPayload$WebViewSettings$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(booleanSerializer)};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    public AdPayload.AdUnit deserialize(Decoder decoder) {
        Object objDecodeNullableSerializableElement;
        Object objDecodeNullableSerializableElement2;
        Object objDecodeNullableSerializableElement3;
        Object objDecodeNullableSerializableElement4;
        Object objDecodeNullableSerializableElement5;
        Object obj;
        Object obj2;
        Object obj3;
        Object obj4;
        Object obj5;
        Object obj6;
        Object objDecodeNullableSerializableElement6;
        Object objDecodeNullableSerializableElement7;
        int i10;
        Object obj7;
        Object obj8;
        Object objDecodeNullableSerializableElement8;
        Object objDecodeNullableSerializableElement9;
        Object obj9;
        Object objDecodeNullableSerializableElement10;
        Object objDecodeNullableSerializableElement11;
        Object obj10;
        Object objDecodeNullableSerializableElement12;
        Object objDecodeNullableSerializableElement13;
        Object objDecodeNullableSerializableElement14;
        Object objDecodeNullableSerializableElement15;
        Object obj11;
        Object objDecodeNullableSerializableElement16;
        Object objDecodeNullableSerializableElement17;
        Object obj12;
        Object obj13;
        Object objDecodeNullableSerializableElement18;
        Object objDecodeNullableSerializableElement19;
        Object objDecodeNullableSerializableElement20;
        Object objDecodeNullableSerializableElement21;
        Object objDecodeNullableSerializableElement22;
        Object objDecodeNullableSerializableElement23;
        Object objDecodeNullableSerializableElement24;
        Object obj14;
        Object objDecodeNullableSerializableElement25;
        Object objDecodeNullableSerializableElement26;
        Object objDecodeNullableSerializableElement27;
        Object objDecodeNullableSerializableElement28;
        Object obj15;
        int i11;
        Object obj16;
        Object obj17;
        int i12;
        int i13;
        int i14;
        Object obj18;
        int i15;
        int i16;
        Object obj19;
        e0.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(descriptor2);
        Object objDecodeNullableSerializableElement29 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            objDecodeNullableSerializableElement13 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 0, stringSerializer, null);
            objDecodeNullableSerializableElement11 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 1, stringSerializer, null);
            Object objDecodeNullableSerializableElement30 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 2, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Object objDecodeNullableSerializableElement31 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 3, intSerializer, null);
            Object objDecodeNullableSerializableElement32 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 4, stringSerializer, null);
            BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
            Object objDecodeNullableSerializableElement33 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 5, booleanSerializer, null);
            objDecodeNullableSerializableElement12 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 6, booleanSerializer, null);
            Object objDecodeNullableSerializableElement34 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 7, booleanSerializer, null);
            Object objDecodeNullableSerializableElement35 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 8, stringSerializer, null);
            objDecodeNullableSerializableElement16 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 9, stringSerializer, null);
            Object objDecodeNullableSerializableElement36 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 10, intSerializer, null);
            objDecodeNullableSerializableElement10 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 11, intSerializer, null);
            Object objDecodeNullableSerializableElement37 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 12, AdPayload.TpatSerializer.INSTANCE, null);
            Object objDecodeNullableSerializableElement38 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 13, stringSerializer, null);
            obj9 = objDecodeNullableSerializableElement37;
            Object objDecodeNullableSerializableElement39 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 14, stringSerializer, null);
            objDecodeNullableSerializableElement8 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 15, stringSerializer, null);
            obj6 = objDecodeNullableSerializableElement38;
            objDecodeNullableSerializableElement17 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 16, new ArrayListSerializer(stringSerializer), null);
            objDecodeNullableSerializableElement7 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 17, new ArrayListSerializer(stringSerializer), null);
            objDecodeNullableSerializableElement6 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 18, AdPayload$ViewAbility$$serializer.INSTANCE, null);
            objDecodeNullableSerializableElement9 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 19, stringSerializer, null);
            Object objDecodeNullableSerializableElement40 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 20, AdPayload$TemplateSettings$$serializer.INSTANCE, null);
            Object objDecodeNullableSerializableElement41 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 21, stringSerializer, null);
            Object objDecodeNullableSerializableElement42 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 22, stringSerializer, null);
            Object objDecodeNullableSerializableElement43 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 23, intSerializer, null);
            Object objDecodeNullableSerializableElement44 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 24, intSerializer, null);
            objDecodeNullableSerializableElement14 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 25, AdPayload$AdSizeInfo$$serializer.INSTANCE, null);
            objDecodeNullableSerializableElement15 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 26, AdPayload$WebViewSettings$$serializer.INSTANCE, null);
            obj8 = objDecodeNullableSerializableElement41;
            obj11 = objDecodeNullableSerializableElement31;
            obj = objDecodeNullableSerializableElement30;
            obj4 = objDecodeNullableSerializableElement35;
            i10 = 536870911;
            objDecodeNullableSerializableElement29 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 27, booleanSerializer, null);
            obj3 = objDecodeNullableSerializableElement34;
            objDecodeNullableSerializableElement5 = objDecodeNullableSerializableElement39;
            obj5 = objDecodeNullableSerializableElement36;
            objDecodeNullableSerializableElement2 = objDecodeNullableSerializableElement44;
            objDecodeNullableSerializableElement3 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 28, booleanSerializer, null);
            objDecodeNullableSerializableElement4 = objDecodeNullableSerializableElement43;
            obj2 = objDecodeNullableSerializableElement32;
            obj10 = objDecodeNullableSerializableElement33;
            obj7 = objDecodeNullableSerializableElement42;
            objDecodeNullableSerializableElement = objDecodeNullableSerializableElement40;
        } else {
            boolean z10 = true;
            int i17 = 0;
            Object objDecodeNullableSerializableElement45 = null;
            Object objDecodeNullableSerializableElement46 = null;
            Object objDecodeNullableSerializableElement47 = null;
            objDecodeNullableSerializableElement = null;
            objDecodeNullableSerializableElement2 = null;
            Object objDecodeNullableSerializableElement48 = null;
            Object objDecodeNullableSerializableElement49 = null;
            Object objDecodeNullableSerializableElement50 = null;
            objDecodeNullableSerializableElement3 = null;
            Object objDecodeNullableSerializableElement51 = null;
            Object objDecodeNullableSerializableElement52 = null;
            objDecodeNullableSerializableElement4 = null;
            Object objDecodeNullableSerializableElement53 = null;
            Object objDecodeNullableSerializableElement54 = null;
            Object obj20 = null;
            Object obj21 = null;
            Object obj22 = null;
            Object obj23 = null;
            Object obj24 = null;
            Object obj25 = null;
            Object obj26 = null;
            Object obj27 = null;
            Object obj28 = null;
            Object obj29 = null;
            Object obj30 = null;
            Object obj31 = null;
            Object obj32 = null;
            objDecodeNullableSerializableElement5 = null;
            while (z10) {
                Object obj33 = objDecodeNullableSerializableElement51;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(descriptor2);
                switch (iDecodeElementIndex) {
                    case -1:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj13 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        i11 = i17;
                        obj16 = obj33;
                        z10 = false;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        i14 = i11;
                        objDecodeNullableSerializableElement50 = obj13;
                        objDecodeNullableSerializableElement51 = obj16;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 0:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj17 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement18 = obj20;
                        i12 = i17 | 1;
                        objDecodeNullableSerializableElement54 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 0, StringSerializer.INSTANCE, objDecodeNullableSerializableElement54);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        i14 = i12;
                        objDecodeNullableSerializableElement47 = obj17;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 1:
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement19 = obj21;
                        i13 = i17 | 2;
                        objDecodeNullableSerializableElement18 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 1, StringSerializer.INSTANCE, obj20);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        i14 = i13;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 2:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj17 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement20 = obj22;
                        i12 = i17 | 4;
                        objDecodeNullableSerializableElement19 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 2, StringSerializer.INSTANCE, obj21);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement18 = obj20;
                        i14 = i12;
                        objDecodeNullableSerializableElement47 = obj17;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 3:
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement21 = obj23;
                        i13 = i17 | 8;
                        objDecodeNullableSerializableElement20 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 3, IntSerializer.INSTANCE, obj22);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        i14 = i13;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 4:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj17 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement22 = obj24;
                        i12 = i17 | 16;
                        objDecodeNullableSerializableElement21 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 4, StringSerializer.INSTANCE, obj23);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        i14 = i12;
                        objDecodeNullableSerializableElement47 = obj17;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 5:
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement23 = obj25;
                        i13 = i17 | 32;
                        objDecodeNullableSerializableElement22 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 5, BooleanSerializer.INSTANCE, obj24);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        i14 = i13;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 6:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj17 = objDecodeNullableSerializableElement47;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement24 = obj26;
                        i12 = i17 | 64;
                        objDecodeNullableSerializableElement23 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 6, BooleanSerializer.INSTANCE, obj25);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        i14 = i12;
                        objDecodeNullableSerializableElement47 = obj17;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 7:
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        obj14 = obj27;
                        i13 = i17 | 128;
                        objDecodeNullableSerializableElement24 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 7, BooleanSerializer.INSTANCE, obj26);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        i14 = i13;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 8:
                        Object obj34 = objDecodeNullableSerializableElement45;
                        obj12 = objDecodeNullableSerializableElement46;
                        obj17 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement25 = obj28;
                        Object objDecodeNullableSerializableElement55 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 8, StringSerializer.INSTANCE, obj27);
                        i12 = i17 | NotificationCompat.FLAG_LOCAL_ONLY;
                        obj14 = objDecodeNullableSerializableElement55;
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = obj34;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        i14 = i12;
                        objDecodeNullableSerializableElement47 = obj17;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 9:
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement26 = obj29;
                        i13 = i17 | 512;
                        objDecodeNullableSerializableElement25 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 9, StringSerializer.INSTANCE, obj28);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        i14 = i13;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 10:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj17 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement27 = obj30;
                        i12 = i17 | 1024;
                        objDecodeNullableSerializableElement26 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 10, IntSerializer.INSTANCE, obj29);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        i14 = i12;
                        objDecodeNullableSerializableElement47 = obj17;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 11:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement28 = obj31;
                        i13 = i17 | 2048;
                        objDecodeNullableSerializableElement27 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 11, IntSerializer.INSTANCE, obj30);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        i14 = i13;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 12:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj17 = objDecodeNullableSerializableElement47;
                        obj15 = obj32;
                        i12 = i17 | 4096;
                        objDecodeNullableSerializableElement28 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 12, AdPayload.TpatSerializer.INSTANCE, obj31);
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        i14 = i12;
                        objDecodeNullableSerializableElement47 = obj17;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 13:
                        Object obj35 = objDecodeNullableSerializableElement45;
                        obj12 = objDecodeNullableSerializableElement46;
                        Object objDecodeNullableSerializableElement56 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 13, StringSerializer.INSTANCE, obj32);
                        i13 = i17 | Segment.SIZE;
                        obj15 = objDecodeNullableSerializableElement56;
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = obj35;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement47 = objDecodeNullableSerializableElement47;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        i14 = i13;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 14:
                        obj12 = objDecodeNullableSerializableElement46;
                        obj13 = objDecodeNullableSerializableElement50;
                        obj16 = obj33;
                        i11 = i17 | 16384;
                        objDecodeNullableSerializableElement5 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 14, StringSerializer.INSTANCE, objDecodeNullableSerializableElement5);
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        i14 = i11;
                        objDecodeNullableSerializableElement50 = obj13;
                        objDecodeNullableSerializableElement51 = obj16;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 15:
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement51 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 15, StringSerializer.INSTANCE, obj33);
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        i14 = i17 | 32768;
                        objDecodeNullableSerializableElement50 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 16:
                        objDecodeNullableSerializableElement50 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 16, new ArrayListSerializer(StringSerializer.INSTANCE), objDecodeNullableSerializableElement50);
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement45 = objDecodeNullableSerializableElement45;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        i14 = i17 | C.DEFAULT_BUFFER_SEGMENT_SIZE;
                        objDecodeNullableSerializableElement51 = obj33;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 17:
                        obj18 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement49 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 17, new ArrayListSerializer(StringSerializer.INSTANCE), objDecodeNullableSerializableElement49);
                        i15 = 131072;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | i15;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 18:
                        obj18 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement48 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 18, AdPayload$ViewAbility$$serializer.INSTANCE, objDecodeNullableSerializableElement48);
                        i15 = 262144;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | i15;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 19:
                        obj18 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement47 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 19, StringSerializer.INSTANCE, objDecodeNullableSerializableElement47);
                        i15 = 524288;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | i15;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 20:
                        obj18 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 20, AdPayload$TemplateSettings$$serializer.INSTANCE, objDecodeNullableSerializableElement);
                        i15 = ExtractorMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | i15;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 21:
                        obj18 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement46 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 21, StringSerializer.INSTANCE, objDecodeNullableSerializableElement46);
                        i15 = 2097152;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | i15;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 22:
                        obj18 = objDecodeNullableSerializableElement50;
                        i16 = i17 | 4194304;
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement53 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 22, StringSerializer.INSTANCE, objDecodeNullableSerializableElement53);
                        i14 = i16;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 23:
                        obj18 = objDecodeNullableSerializableElement50;
                        i16 = i17 | 8388608;
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement4 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 23, IntSerializer.INSTANCE, objDecodeNullableSerializableElement4);
                        i14 = i16;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 24:
                        obj18 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement2 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 24, IntSerializer.INSTANCE, objDecodeNullableSerializableElement2);
                        i15 = 16777216;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | i15;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 25:
                        obj18 = objDecodeNullableSerializableElement50;
                        i16 = i17 | 33554432;
                        obj12 = objDecodeNullableSerializableElement46;
                        objDecodeNullableSerializableElement52 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 25, AdPayload$AdSizeInfo$$serializer.INSTANCE, objDecodeNullableSerializableElement52);
                        i14 = i16;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 26:
                        obj18 = objDecodeNullableSerializableElement50;
                        objDecodeNullableSerializableElement45 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 26, AdPayload$WebViewSettings$$serializer.INSTANCE, objDecodeNullableSerializableElement45);
                        i15 = 67108864;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | i15;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement50 = obj18;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 27:
                        obj19 = objDecodeNullableSerializableElement50;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | 134217728;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement29 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 27, BooleanSerializer.INSTANCE, objDecodeNullableSerializableElement29);
                        objDecodeNullableSerializableElement50 = obj19;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    case 28:
                        obj19 = objDecodeNullableSerializableElement50;
                        obj12 = objDecodeNullableSerializableElement46;
                        i14 = i17 | 268435456;
                        objDecodeNullableSerializableElement18 = obj20;
                        objDecodeNullableSerializableElement19 = obj21;
                        objDecodeNullableSerializableElement20 = obj22;
                        objDecodeNullableSerializableElement21 = obj23;
                        objDecodeNullableSerializableElement22 = obj24;
                        objDecodeNullableSerializableElement23 = obj25;
                        objDecodeNullableSerializableElement24 = obj26;
                        obj14 = obj27;
                        objDecodeNullableSerializableElement25 = obj28;
                        objDecodeNullableSerializableElement26 = obj29;
                        objDecodeNullableSerializableElement27 = obj30;
                        objDecodeNullableSerializableElement28 = obj31;
                        obj15 = obj32;
                        objDecodeNullableSerializableElement51 = obj33;
                        objDecodeNullableSerializableElement3 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor2, 28, BooleanSerializer.INSTANCE, objDecodeNullableSerializableElement3);
                        objDecodeNullableSerializableElement50 = obj19;
                        i17 = i14;
                        objDecodeNullableSerializableElement46 = obj12;
                        obj32 = obj15;
                        obj31 = objDecodeNullableSerializableElement28;
                        obj30 = objDecodeNullableSerializableElement27;
                        obj20 = objDecodeNullableSerializableElement18;
                        obj21 = objDecodeNullableSerializableElement19;
                        obj22 = objDecodeNullableSerializableElement20;
                        obj23 = objDecodeNullableSerializableElement21;
                        obj24 = objDecodeNullableSerializableElement22;
                        obj25 = objDecodeNullableSerializableElement23;
                        obj26 = objDecodeNullableSerializableElement24;
                        obj27 = obj14;
                        obj28 = objDecodeNullableSerializableElement25;
                        obj29 = objDecodeNullableSerializableElement26;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            Object obj36 = objDecodeNullableSerializableElement45;
            Object obj37 = objDecodeNullableSerializableElement51;
            obj = obj21;
            obj2 = obj23;
            obj3 = obj26;
            obj4 = obj27;
            obj5 = obj29;
            obj6 = obj32;
            Object obj38 = objDecodeNullableSerializableElement50;
            objDecodeNullableSerializableElement6 = objDecodeNullableSerializableElement48;
            objDecodeNullableSerializableElement7 = objDecodeNullableSerializableElement49;
            i10 = i17;
            obj7 = objDecodeNullableSerializableElement53;
            obj8 = objDecodeNullableSerializableElement46;
            objDecodeNullableSerializableElement8 = obj37;
            objDecodeNullableSerializableElement9 = objDecodeNullableSerializableElement47;
            obj9 = obj31;
            objDecodeNullableSerializableElement10 = obj30;
            objDecodeNullableSerializableElement11 = obj20;
            obj10 = obj24;
            objDecodeNullableSerializableElement12 = obj25;
            objDecodeNullableSerializableElement13 = objDecodeNullableSerializableElement54;
            objDecodeNullableSerializableElement14 = objDecodeNullableSerializableElement52;
            objDecodeNullableSerializableElement15 = obj36;
            obj11 = obj22;
            objDecodeNullableSerializableElement16 = obj28;
            objDecodeNullableSerializableElement17 = obj38;
        }
        compositeDecoderBeginStructure.endStructure(descriptor2);
        return new AdPayload.AdUnit(i10, (String) objDecodeNullableSerializableElement13, (String) objDecodeNullableSerializableElement11, (String) obj, (Integer) obj11, (String) obj2, (Boolean) obj10, (Boolean) objDecodeNullableSerializableElement12, (Boolean) obj3, (String) obj4, (String) objDecodeNullableSerializableElement16, (Integer) obj5, (Integer) objDecodeNullableSerializableElement10, (Map) obj9, (String) obj6, (String) objDecodeNullableSerializableElement5, (String) objDecodeNullableSerializableElement8, (List) objDecodeNullableSerializableElement17, (List) objDecodeNullableSerializableElement7, (AdPayload.ViewAbility) objDecodeNullableSerializableElement6, (String) objDecodeNullableSerializableElement9, (AdPayload.TemplateSettings) objDecodeNullableSerializableElement, (String) obj8, (String) obj7, (Integer) objDecodeNullableSerializableElement4, (Integer) objDecodeNullableSerializableElement2, (AdPayload.AdSizeInfo) objDecodeNullableSerializableElement14, (AdPayload.WebViewSettings) objDecodeNullableSerializableElement15, (Boolean) objDecodeNullableSerializableElement29, (Boolean) objDecodeNullableSerializableElement3, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(Encoder encoder, AdPayload.AdUnit value) {
        e0.checkNotNullParameter(encoder, "encoder");
        e0.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(descriptor2);
        AdPayload.AdUnit.write$Self(value, compositeEncoderBeginStructure, descriptor2);
        compositeEncoderBeginStructure.endStructure(descriptor2);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}
