package com.bytedance.sdk.openadsdk.multipro.xsB;

/* loaded from: classes2.dex */
public class LJjmO {
    public static String CHyxbq;
    public static String CnGfZiI;
    public static String DHDfsEhq;
    public static String DPhFfdc;
    public static String FtDoVR;
    public static String FvuR;
    public static String NOMxPoe;
    public static String NYNHllLQKIZBOcI;
    public static String NZHgjNegixXhWT;
    public static String NgdwxqSibYf;
    public static String OmRVImk;
    public static String PkseFUSUvmNHI;
    public static String RDGmIUHqmyM;
    public static String VDOZRIHcNmyywdH;
    public static String VSADxwFrvpLncR;
    public static String VUbARo;
    public static String VligPs;
    public static String WIiUVMB;
    public static String XOjJa;
    public static String Xbz;
    public static String ZSCOhzvhETiOpZ;
    public static String bGryFrCyxN;
    public static String cAEZGPUy;
    public static String ciUw;
    public static String dqGcEqPozgZKf;
    public static String guCUswShaS;
    public static String hmHAavjuE;
    public static String jfUm;
    public static String jleESrfCSiS;
    public static String lXqO;
    public static String mtIKxiEcy;
    public static String nTvlS;
    public static String pFbO;
    public static String pNwXFlPwPZhv;
    public static String pVwjiP;
    public static String pfU;
    public static String rtScCcck;
    public static String sLXPWHTLTIWCwKp;
    public static String uvAydwjXrSE;
    public static String wLWgVHzUIOI;
    public static String wWE;
    public static String xUog;
    public static String xniJZpw;
    public static String ygXlMdh;
}
