package com.bytedance.sdk.openadsdk.oya;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.dt;
import com.bytedance.sdk.openadsdk.utils.hna;
import com.bytedance.sdk.openadsdk.utils.va;

/* compiled from: r8-map-id-329fa88356c9e071bedcd87e8cbc16a4cb0c028932e63902b8210957806638ae */
/* loaded from: classes4.dex */
public class au extends com.bytedance.sdk.openadsdk.core.jj.qk {
    public au(Context context) {
        this(context, null);
    }

    private void jpo(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.jj.qk qkVar = new com.bytedance.sdk.openadsdk.core.jj.qk(context);
        qkVar.setId(hna.czp);
        qkVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        qkVar.setBackgroundColor(0);
        qkVar.setGravity(17);
        addView(qkVar);
        View cmVar = new com.bytedance.sdk.openadsdk.core.jj.cm(context);
        cmVar.setId(hna.pzk);
        cmVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        qkVar.addView(cmVar);
        com.bytedance.sdk.openadsdk.core.jj.jj jjVar = new com.bytedance.sdk.openadsdk.core.jj.jj(context);
        jjVar.setId(hna.f21550sn);
        int iJd = va.jd(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(iJd, iJd);
        layoutParams.addRule(13);
        jjVar.setLayoutParams(layoutParams);
        jjVar.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_video_loading_progress_bar"));
        qkVar.addView(jjVar);
        com.bytedance.sdk.openadsdk.core.jj.my myVar = new com.bytedance.sdk.openadsdk.core.jj.my(context);
        myVar.setId(hna.zrw);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        myVar.setLayoutParams(layoutParams2);
        myVar.setGravity(1);
        myVar.setOrientation(1);
        myVar.setVisibility(8);
        qkVar.addView(myVar);
        com.bytedance.sdk.openadsdk.core.jj.cm cmVar2 = new com.bytedance.sdk.openadsdk.core.jj.cm(context);
        cmVar2.setId(hna.f21525hk);
        cmVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        cmVar2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        cmVar2.setScaleType(scaleType);
        myVar.addView(cmVar2);
        com.bytedance.sdk.openadsdk.core.jj.xyk xykVar = new com.bytedance.sdk.openadsdk.core.jj.xyk(context);
        xykVar.setId(hna.zmh);
        xykVar.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        xykVar.setText(dt.jpo(context, "tt_video_retry_des_txt"));
        xykVar.setTextColor(Color.parseColor("#999999"));
        myVar.addView(xykVar);
        com.bytedance.sdk.openadsdk.core.jj.cm cmVar3 = new com.bytedance.sdk.openadsdk.core.jj.cm(context);
        cmVar3.setId(hna.fgt);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        cmVar3.setLayoutParams(layoutParams3);
        cmVar3.setScaleType(scaleType);
        cmVar3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_play_movebar_textpage"));
        cmVar3.setVisibility(8);
        addView(cmVar3);
        com.bytedance.sdk.openadsdk.core.jj.cm cmVar4 = new com.bytedance.sdk.openadsdk.core.jj.cm(context);
        cmVar4.setId(hna.f21542ou);
        int iJd2 = va.jd(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(iJd2, iJd2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int iJd3 = va.jd(context, 7.0f);
        layoutParams4.setMarginEnd(iJd3);
        layoutParams4.rightMargin = iJd3;
        layoutParams4.topMargin = iJd3;
        cmVar4.setLayoutParams(layoutParams4);
        cmVar4.setBackground(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_detail_video_btn_bg"));
        cmVar4.setScaleType(scaleType);
        cmVar4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_close_move_detail"));
        addView(cmVar4);
        com.bytedance.sdk.openadsdk.core.jj.xyk xykVar2 = new com.bytedance.sdk.openadsdk.core.jj.xyk(context);
        xykVar2.setId(hna.kye);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        xykVar2.setLayoutParams(layoutParams5);
        xykVar2.setBackground(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        xykVar2.setEllipsize(truncateAt);
        xykVar2.setMaxLines(2);
        int iJd4 = va.jd(context, 15.0f);
        xykVar2.setPadding(iJd4, va.jd(context, 14.0f), iJd4, 0);
        xykVar2.setSingleLine(false);
        xykVar2.setTextColor(-1);
        xykVar2.setTextSize(2, 17.0f);
        xykVar2.setVisibility(8);
        addView(xykVar2);
        com.bytedance.sdk.openadsdk.core.jj.qk qkVar2 = new com.bytedance.sdk.openadsdk.core.jj.qk(context);
        qkVar2.setId(hna.iwg);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        qkVar2.setLayoutParams(layoutParams6);
        qkVar2.setBackground(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_video_black_desc_gradient"));
        qkVar2.setGravity(16);
        qkVar2.setVisibility(8);
        addView(qkVar2);
        com.bytedance.sdk.openadsdk.core.jj.cm cmVar5 = new com.bytedance.sdk.openadsdk.core.jj.cm(context);
        int i10 = hna.fri;
        cmVar5.setId(i10);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int iJd5 = va.jd(context, 12.0f);
        layoutParams7.leftMargin = iJd5;
        layoutParams7.setMarginStart(iJd5);
        cmVar5.setLayoutParams(layoutParams7);
        cmVar5.setScaleType(scaleType);
        cmVar5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_leftbackbutton_titlebar_photo_preview"));
        qkVar2.addView(cmVar5);
        com.bytedance.sdk.openadsdk.core.jj.xyk xykVar3 = new com.bytedance.sdk.openadsdk.core.jj.xyk(context);
        xykVar3.setId(hna.f21565zq);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int iJd6 = va.jd(context, 16.0f);
        layoutParams8.leftMargin = iJd6;
        layoutParams8.rightMargin = iJd;
        layoutParams8.setMarginStart(iJd6);
        layoutParams8.setMarginEnd(iJd);
        layoutParams8.addRule(17, i10);
        int i11 = hna.f21523fp;
        layoutParams8.addRule(0, i11);
        layoutParams8.addRule(1, i10);
        layoutParams8.addRule(16, i11);
        xykVar3.setLayoutParams(layoutParams8);
        xykVar3.setEllipsize(truncateAt);
        xykVar3.setGravity(16);
        xykVar3.setMaxLines(1);
        xykVar3.setSingleLine(true);
        xykVar3.setTextColor(-1);
        xykVar3.setTextSize(2, 17.0f);
        qkVar2.addView(xykVar3);
        com.bytedance.sdk.openadsdk.core.jj.my myVar2 = new com.bytedance.sdk.openadsdk.core.jj.my(context);
        myVar2.setId(i11);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int iJd7 = va.jd(context, 14.0f);
        layoutParams9.rightMargin = iJd7;
        layoutParams9.setMarginEnd(iJd7);
        myVar2.setLayoutParams(layoutParams9);
        myVar2.setGravity(16);
        myVar2.setOrientation(1);
        qkVar2.addView(myVar2);
        com.bytedance.sdk.openadsdk.core.jj.xyk xykVar4 = new com.bytedance.sdk.openadsdk.core.jj.xyk(context);
        xykVar4.setId(hna.f21537mg);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        xykVar4.setLayoutParams(layoutParams10);
        xykVar4.setGravity(16);
        xykVar4.setMaxLines(1);
        xykVar4.setSingleLine(true);
        xykVar4.setTextColor(-1);
        xykVar4.setTextSize(2, 12.0f);
        myVar2.addView(xykVar4);
        com.bytedance.sdk.openadsdk.core.jj.my myVar3 = new com.bytedance.sdk.openadsdk.core.jj.my(context);
        myVar3.setId(hna.ted);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, va.jd(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        myVar3.setLayoutParams(layoutParams11);
        myVar3.setGravity(16);
        myVar3.setOrientation(0);
        myVar3.setVisibility(8);
        addView(myVar3);
        com.bytedance.sdk.openadsdk.core.jj.xyk xykVar5 = new com.bytedance.sdk.openadsdk.core.jj.xyk(context);
        xykVar5.setId(hna.ozw);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = iJd6;
        layoutParams12.rightMargin = iJd5;
        layoutParams12.setMarginEnd(iJd5);
        layoutParams12.setMarginStart(iJd6);
        xykVar5.setLayoutParams(layoutParams12);
        xykVar5.setText(dt.jpo(context, "tt_00_00"));
        xykVar5.setTextColor(-1);
        xykVar5.setTextSize(2, 10.0f);
        myVar3.addView(xykVar5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(hna.f21560xp);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, va.jd(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        myVar3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.jj.xyk xykVar6 = new com.bytedance.sdk.openadsdk.core.jj.xyk(context);
        xykVar6.setId(hna.clt);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = iJd5;
        layoutParams14.rightMargin = iJd6;
        layoutParams14.setMarginEnd(iJd6);
        layoutParams14.setMarginStart(iJd5);
        xykVar6.setLayoutParams(layoutParams14);
        xykVar6.setText(dt.jpo(context, "tt_00_00"));
        xykVar6.setTextColor(-1);
        xykVar6.setTextSize(2, 10.0f);
        myVar3.addView(xykVar6);
        com.bytedance.sdk.openadsdk.core.jj.cm cmVar6 = new com.bytedance.sdk.openadsdk.core.jj.cm(context);
        cmVar6.setId(hna.f21545ql);
        cmVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        cmVar6.setPadding(iJd6, 0, iJd6, 0);
        cmVar6.setScaleType(scaleType);
        cmVar6.setVisibility(8);
        cmVar6.setImageDrawable(dt.wqx(context, "tt_enlarge_video"));
        myVar3.addView(cmVar6);
        View cif = new Cif(context);
        cif.setId(hna.uhu);
        cif.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(cif);
        com.bytedance.sdk.openadsdk.core.jj.xyk xykVar7 = new com.bytedance.sdk.openadsdk.core.jj.xyk(context);
        xykVar7.setId(hna.f21522fc);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = iJd5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        xykVar7.setLayoutParams(layoutParams15);
        xykVar7.setBackgroundColor(Color.parseColor("#00000000"));
        xykVar7.setText("close");
        xykVar7.setMinHeight(va.jd(context, 44.0f));
        xykVar7.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.ju.jpo(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(xykVar7);
    }

    public au(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public au(Context context, AttributeSet attributeSet, int i10) {
        super(context, attributeSet, i10);
        jpo(context);
    }
}
