# Config Paid
type=freemium
max_game=3
apikey=9R5E2JZHUGHAZ6Q91LKP
gcm_key=796950833935
upgradeProductId=com.digidust.elokence.akinator.paid.full
publisherPublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnkixiP3CCMCEEQYSaLwal05yC5m/ngBbq1dwVdTaXflC2G4npT33SVUtj41X2CJMtVV3H+yORCwv/fp425lXlrZ9BlSq7NLUbMdxB8mQ2hMqQvY48bYjQaxKLeARUUnbUskcwQmNEHPOz+mr0oBIl4T3G7h6/HSGu8bgy4wTru3Na3CdU4w7nYekBbSW23JdOt1BO3BkMmq9ClcJoPd3aRjCfFALZgWWpNXi2kVmF0zTDTQo/S7DKg6HGjJn5d2hRN0DmwH9DNFbmmCsKcwHdCC4VLhDAxhnZqZJb4NgMsiPJE3irSJ4uMam2td5LcwJPwWXRAG6l2qVQj8cjcvGHwIDAQAB
foreground_colors=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwgFSBk3/I6elqXQrBerzfEwXW5I99uXnAfl3TSpDE+OwzNK5rQGQTAlDUMdltiF2hZIq1I0ilhxpiQtEK5SuHJXtdnN7OS5J14h47enyLXEYQMGvrWOwPRTjh4XsHBa0wiw9FZxDftmfXYx0kI74jZG5ZrlsJo+7W1ndBEL0iAdJdSgAmj/soOpA+gEXo0S9wmauWIHK034DOykgFIDyo6OfBHhWTOTlXZ8rkQnHPK5EVAcozgwYRCRmbpGUBIjdLq1A9ytaiSf8mZPsNZ0ypPIdumIFJdghOZmguVI4QCh+FFCktEtVDMBbhGdAvtXnYrIBW6eSv668BYDPsuwyRQIDAQAB
