# Config Paid
type=paid
apikey=FHHCWU3FTAGYRVHUAKZY
gcm_key=796950833935
publisherPublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnkixiP3CCMCEEQYSaLwal05yC5m/ngBbq1dwVdTaXflC2G4npT33SVUtj41X2CJMtVV3H+yORCwv/fp425lXlrZ9BlSq7NLUbMdxB8mQ2hMqQvY48bYjQaxKLeARUUnbUskcwQmNEHPOz+mr0oBIl4T3G7h6/HSGu8bgy4wTru3Na3CdU4w7nYekBbSW23JdOt1BO3BkMmq9ClcJoPd3aRjCfFALZgWWpNXi2kVmF0zTDTQo/S7DKg6HGjJn5d2hRN0DmwH9DNFbmmCsKcwHdCC4VLhDAxhnZqZJb4NgMsiPJE3irSJ4uMam2td5LcwJPwWXRAG6l2qVQj8cjcvGHwIDAQAB
partnerId=420